SgEnum = {
  AddonMessageType = {
    AddonInfo = 0,
    Heartbeat = 1,
    PlayerConnectionCheck = 2,
    EnteredCombat = 11,
    ExitedCombat = 12,
    LoggingOut = 13,
    LogoutCancelled = 14,
    HealthLow = 15,
    HealthCriticallyLow = 16,
    SpellCastStarted = 17,
    SpellCastInterrupted = 18,
    LossOfControl = 19,
    ExtraAttacksStored = 20
  },
  LossOfControlType = {
    Unknown = 0,
    Confuse = 1,
    Disarm = 2,
    Root = 3,
    SchoolInterrupt = 4,
    Silence = 5,
    Stun = 6,
    StunMechanic = 7,
    Fear = 8,
    FearMechanic = 9,
  },
  NotificationType = {
    PlayerDisconnected = 1,
    PlayerReconnected = 2,
    PlayerOffline = 3,
    EnteredCombat = 11,
    LoggingOut = 13,
    LogoutCancelled = 14,
    HealthLow = 15,
    HealthCriticallyLow = 16,
    SpellCastStarted = 17,
    SpellCastInterrupted = 18,
    LossOfControl = 19,
    AuraApplied = 20,
    PvpFlagged = 21,
    PvpUnflagged = 22,
    ExtraAttacksStored = 23,
  },
}